src/Entity/Propertys.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\PropertysRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PropertysRepository::class)]
class Propertys
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $code = null;

    #[ORM\Column]
    private ?float $surface = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    
   
    private ?float $prix = null;

    #[ORM\Column]
    
   
    private ?int $chambres = null;

    #[ORM\Column]
   
    private ?int $salle_bains = null;

    #[ORM\Column]
    
    private ?int $etages = null;

    #[ORM\Column]
    private ?int $numero_etage = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    #[ORM\Column]
 
    private ?int $code_postale = null;

    #[ORM\Column(length: 100)]
    private ?string $region = null;

    #[ORM\Column(nullable: true)]
    private ?bool $internet = null;

    #[ORM\Column(nullable: true)]
    private ?bool $balcon = null;

    #[ORM\Column(nullable: true)]
    private ?bool $garage = null;

    #[ORM\Column(nullable: true)]
    private ?bool $gym = null;

    #[ORM\Column(nullable: true)]
    private ?bool $piscine = null;

    #[ORM\Column(nullable: true)]
    private ?bool $camera = null;

    #[ORM\Column(type: Types::BINARY)]
    #[Assert\Image(
        minWidth: 200,
        maxWidth: 400,
        minHeight: 200,
        maxHeight: 400,
    )]
    private $image = null;

    #[ORM\Column]

    private ?DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    
    private ?DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'propertys')]
    private ?Users $user = null;

    #[ORM\OneToMany(mappedBy: 'propertys', targetEntity: Medias::class)]
    private Collection $medias;

    #[ORM\ManyToOne(inversedBy: 'propertys')]
    private ?Categorys $categorys = null;

    #[ORM\ManyToOne(inversedBy: 'propertys')]
    private ?TypeProperty $typeprops = null;

    public function __construct()
    {
        $this->createdAt=new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
        $this->medias = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getSurface(): ?float
    {
        return $this->surface;
    }

    public function setSurface(float $surface): static
    {
        $this->surface = $surface;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getChambres(): ?int
    {
        return $this->chambres;
    }

    public function setChambres(int $chambres): static
    {
        $this->chambres = $chambres;

        return $this;
    }

    public function getSalleBains(): ?int
    {
        return $this->salle_bains;
    }

    public function setSalleBains(int $salle_bains): static
    {
        $this->salle_bains = $salle_bains;

        return $this;
    }

    public function getEtages(): ?int
    {
        return $this->etages;
    }

    public function setEtages(int $etages): static
    {
        $this->etages = $etages;

        return $this;
    }

    public function getNumeroEtage(): ?int
    {
        return $this->numero_etage;
    }

    public function setNumeroEtage(int $numero_etage): static
    {
        $this->numero_etage = $numero_etage;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostale(): ?int
    {
        return $this->code_postale;
    }

    public function setCodePostale(int $code_postale): static
    {
        $this->code_postale = $code_postale;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): static
    {
        $this->region = $region;

        return $this;
    }

    public function isInternet(): ?bool
    {
        return $this->internet;
    }

    public function setInternet(?bool $internet): static
    {
        $this->internet = $internet;

        return $this;
    }

    public function isBalcon(): ?bool
    {
        return $this->balcon;
    }

    public function setBalcon(?bool $balcon): static
    {
        $this->balcon = $balcon;

        return $this;
    }

    public function isGarage(): ?bool
    {
        return $this->garage;
    }

    public function setGarage(?bool $garage): static
    {
        $this->garage = $garage;

        return $this;
    }

    public function isGym(): ?bool
    {
        return $this->gym;
    }

    public function setGym(?bool $gym): static
    {
        $this->gym = $gym;

        return $this;
    }

    public function isPiscine(): ?bool
    {
        return $this->piscine;
    }

    public function setPiscine(?bool $piscine): static
    {
        $this->piscine = $piscine;

        return $this;
    }

    public function isCamera(): ?bool
    {
        return $this->camera;
    }

    public function setCamera(?bool $camera): static
    {
        $this->camera = $camera;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Medias>
     */
    public function getMedias(): Collection
    {
        return $this->medias;
    }

    public function addMedia(Medias $media): static
    {
        if (!$this->medias->contains($media)) {
            $this->medias->add($media);
            $media->setPropertys($this);
        }

        return $this;
    }

    public function removeMedia(Medias $media): static
    {
        if ($this->medias->removeElement($media)) {
            // set the owning side to null (unless already changed)
            if ($media->getPropertys() === $this) {
                $media->setPropertys(null);
            }
        }

        return $this;
    }

    public function getCategorys(): ?Categorys
    {
        return $this->categorys;
    }

    public function setCategorys(?Categorys $categorys): static
    {
        $this->categorys = $categorys;

        return $this;
    }

    public function getTypeprops(): ?TypeProperty
    {
        return $this->typeprops;
    }

    public function setTypeprops(?TypeProperty $typeprops): static
    {
        $this->typeprops = $typeprops;

        return $this;
    }
}

src/Form/PropertysType.php
<?php

namespace App\Form;

use App\Entity\Propertys;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertysType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        
            ->add('code')
            ->add('surface')
            ->add('description')
            ->add('prix')
            ->add('chambres')
            ->add('salle_bains')
            ->add('etages')
            ->add('numero_etage')
            ->add('adresse')
            ->add('ville')
            ->add('code_postale')
            ->add('region')
            ->add('internet')
            ->add('balcon')
            ->add('garage')
            ->add('gym')
            ->add('piscine')
            ->add('camera')
            ->add('image')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Propertys::class,
        ]);
    }
}

src/Controller/PropertysController.php
<?php

namespace App\Controller;

use App\Entity\Propertys;
use App\Form\PropertysType;
use App\Repository\PropertysRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/propertys')]
class PropertysController extends AbstractController
{
    #[Route('/', name: 'app_propertys_index', methods: ['GET'])]
    public function index(PropertysRepository $propertysRepository): Response
    {
        return $this->render('propertys/index.html.twig', [
            'propertys' => $propertysRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_propertys_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $property = new Propertys();
        $form = $this->createForm(PropertysType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($property);
            $entityManager->flush();

            return $this->redirectToRoute('app_propertys_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('propertys/new.html.twig', [
            'property' => $property,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_propertys_show', methods: ['GET'])]
    public function show(Propertys $property): Response
    {
        return $this->render('propertys/show.html.twig', [
            'property' => $property,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_propertys_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Propertys $property, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PropertysType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_propertys_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('propertys/edit.html.twig', [
            'property' => $property,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_propertys_delete', methods: ['POST'])]
    public function delete(Request $request, Propertys $property, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$property->getId(), $request->request->get('_token'))) {
            $entityManager->remove($property);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_propertys_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/propertys/_delete_form.html.twig
<form method="post" action="{{ path('app_propertys_delete', {'id': property.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ property.id) }}">
    <button class="btn">Delete</button>
</form>

templates/propertys/_form.html.twig
<div class="container m-5">
    <h1 class="m-4">Création d'une Property</h1>

    {# read and display just one flash message type #}
    {# {% for message in app.flashes('success') %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %} #}
    {{ form_start(form) }}
<div class="card">
    <div class="container">
        
        <div class="row">
            <h3 class="m-4">Infos Détails</h3>
            <div class="form-group col-6">
                {{ form_label(form.code) }}
                {{ form_widget(form.code) }}
                <div class="form-error">
                    {{ form_errors(form.code) }}
                </div>
            </div>

            <div class="form-group col-6">
                {{ form_label(form.surface) }}
                {{ form_widget(form.surface) }}
                <div class="form-error">
                    {{ form_errors(form.surface) }}
                </div>
            </div>

            <div class="form-group col-6">
                {{ form_label(form.chambres) }}
                {{ form_widget(form.chambres) }}
                <div class="form-error">
                    {{ form_errors(form.chambres) }}
                </div>
            </div>

            <div class="form-group col-6">
                {{ form_label(form.prix) }}
                {{ form_widget(form.prix) }}
                <div class="form-error">
                    {{ form_errors(form.prix) }}
                </div>
            </div>
        </div>
    </div>

    <div class="container mb-4">
        <div class="row">
            <div class="form-group col-4">
                {{ form_label(form.numero_etage) }}
                {{ form_widget(form.numero_etage) }}
                <div class="form-error">
                    {{ form_errors(form.numero_etage) }}
                </div>
            </div>
            <div class="form-group col-4">
                {{ form_label(form.etages) }}
                {{ form_widget(form.etages) }}
                <div class="form-error">
                    {{ form_errors(form.etages) }}
                </div>
            </div>

            <div class="form-group col-4">
                {{ form_label(form.salle_bains) }}
                {{ form_widget(form.salle_bains) }}
                <div class="form-error">
                    {{ form_errors(form.salle_bains) }}
                </div>
            </div>


        </div>
    </div>
</div>
<br>
<div class="card">
    <div class="container m-2">
      
        <div class="row">
            <h3>Loclaisation</h3>
            <div class="form-group col-6">
                {{ form_label(form.adresse) }}
                {{ form_widget(form.adresse) }}
                <div class="form-error">
                    {{ form_errors(form.adresse) }}
                </div>
            </div>
            <div class="form-group col-6">
                {{ form_label(form.ville) }}
                {{ form_widget(form.ville) }}
                <div class="form-error">
                    {{ form_errors(form.ville) }}
                </div>
            </div>

            <div class="form-group col-6">
                {{ form_label(form.code_postale) }}
                {{ form_widget(form.code_postale) }}
                <div class="form-error">
                    {{ form_errors(form.code_postale) }}
                </div>
            </div>

            <div class="form-group col-6">
                {{ form_label(form.region) }}
                {{ form_widget(form.region) }}
                <div class="form-error">
                    {{ form_errors(form.region) }}
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="card mb-4">
    <div class="container">
        <div class="row">
            <h3 class="m-4">Installations</h3>
            <div class="col-4">{{ form_row(form.internet, {label_attr: {class: 'checkbox-custom'} }) }}</div>
            <div class="col-4">{{ form_row(form.balcon, {label_attr: {class: 'checkbox-custom'} }) }}</div>
            <div class="col-4">{{ form_row(form.gym, {label_attr: {class: 'checkbox-custom'} }) }}</div>
            <div class="col-4">{{ form_row(form.piscine, {label_attr: {class: 'checkbox-custom'} }) }}</div>
            <div class="col-4">{{ form_row(form.garage, {label_attr: {class: 'checkbox-custom'} }) }}</div>
            <div class="col-4">{{ form_row(form.camera, {label_attr: {class: 'checkbox-custom'} }) }}</div>
        </div>
    </div>
</div>

   

        <div>{{ form_row(form.image, {label_attr: {class: 'image'} }) }}</div>

        <div class="form-group">
            {{ form_label(form.description) }}
            {{ form_widget(form.description) }}
            <div class="form-error">
                {{ form_errors(form.description) }}
            </div>
        </div>
        <div class="form-group mt-4">
            {{ form_widget(form) }}
            <button class="btn btn-primary">{{ button_label|default('Save') }}</button>

        </div>
 


    {{ form_end(form) }}
</div>

templates/propertys/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Propertys{% endblock %}

{% block body %}
    <h1>Edit Propertys</h1>

    {{ include('propertys/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_propertys_index') }}">back to list</a>

    {{ include('propertys/_delete_form.html.twig') }}
{% endblock %}

templates/propertys/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propertys index{% endblock %}

{% block body %}
<div class="w-100 m-4">
    <h1>Annonce index</h1>

    <div class="container">
        <div class="row">
          
            {% for property in propertys %}
            <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card m-3">
                <div class="m-2">{{(property.image) }}</div>
                <div class="m-2">
                <p><strong>Code:</strong>{{ (property.code) }}</p>
                <p><strong>Surface:</strong>{{ (property.surface) }}<strong>M²</strong></p>
                <p><strong>Prix:</strong>{{ (property.prix) }} <strong>€</strong></p>
                <p><strong>Description:</strong>{{ (property.description) }}</p>
                <p><strong>Chambres:</strong>{{ (property.chambres) }}</p>
                <p><strong>Salle de Bains:</strong>{{ (property.salleBains) }}</p>
                <p><strong>Number des Etages:</strong>{{ (property.etages) }}</p>
                <p><strong>Numero-Etage:</strong>{{ (property.numeroEtage) }}</p>
                <p><strong>Adresse:</strong>{{ (property.adresse) }}</p>
                <p><strong>Ville:</strong>{{( property.ville) }}</p>
                <p><strong>Code-Postale:</strong>{{ (property.codePostale) }}</p>
                <p><strong>Region:</strong>{{ (property.region) }}</p>
                <p><strong>Publier à :</strong>{{ (property.createdAt ? property.createdAt|date('Y-m-d H:i:s') : '') }}</p>
               

            
                <p><strong>Internet :</strong>{{ property.internet ? 'Yes' : 'No' }}</p>
                <p><strong>Balcon :</strong>{{ property.balcon ? 'Yes' : 'No' }}</p>
                <p><strong>Garage :</strong>{{ property.garage ? 'Yes' : 'No' }}</p>
                <p><strong>Salle de sport :</strong>{{ property.gym ? 'Yes' : 'No' }}</p>
                <p><strong>Piscine :</strong>{{ property.piscine ? 'Yes' : 'No' }}</p>
                <p><strong>Camera :</strong>{{ property.camera ? 'Yes' : 'No' }}</p>
            
            </div>

                <div>
                    <a class="btn btn-primary m-4" href="{{ path('app_propertys_show', {'id': property.id}) }}"
                        role="button">show</a>
                    <a class="btn btn-primary m-4" href="{{ path('app_propertys_edit', {'id': property.id}) }}"
                        role="button">edit</a>
                </div>

            </div>
        </div>
        
           
        
            {% endfor %}
        </div>
    </div>
</div>


<a  class="btn btn-primary m-4" href="{{ path('app_propertys_new') }}">Create new</a>
{% endblock %}

templates/propertys/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Propertys{% endblock %}

{% block body %}
   
    {{ include('propertys/_form.html.twig') }}

    <a class="btn btn-primary m-4" href="{{ path('app_propertys_index') }}">back to list</a>
{% endblock %}

templates/propertys/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Propertys{% endblock %}

{% block body %}
    <h1>Propertys</h1>

    <table class="table">
        <tbody>
           
            <tr>
                <th>Code</th>
                <td>{{ property.code }}</td>
            </tr>
            <tr>
                <th>Surface</th>
                <td>{{ property.surface }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ property.description }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ property.prix }}</td>
            </tr>
            <tr>
                <th>Chambres</th>
                <td>{{ property.chambres }}</td>
            </tr>
            <tr>
                <th>Salle_bains</th>
                <td>{{ property.salleBains }}</td>
            </tr>
            <tr>
                <th>Etages</th>
                <td>{{ property.etages }}</td>
            </tr>
            <tr>
                <th>Numero_etage</th>
                <td>{{ property.numeroEtage }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ property.adresse }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ property.ville }}</td>
            </tr>
            <tr>
                <th>Code_postale</th>
                <td>{{ property.codePostale }}</td>
            </tr>
            <tr>
                <th>Region</th>
                <td>{{ property.region }}</td>
            </tr>
            <tr>
                <th>Internet</th>
                <td>{{ property.internet ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Balcon</th>
                <td>{{ property.balcon ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Garage</th>
                <td>{{ property.garage ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Gym</th>
                <td>{{ property.gym ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Piscine</th>
                <td>{{ property.piscine ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Camera</th>
                <td>{{ property.camera ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ property.image }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ property.createdAt ? property.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
           
        </tbody>
    </table>

    <a href="{{ path('app_propertys_index') }}">back to list</a>

    <a href="{{ path('app_propertys_edit', {'id': property.id}) }}">edit</a>

    {{ include('propertys/_delete_form.html.twig') }}
{% endblock %}